version: '3.8'
services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    expose:
      - 4000
    command: mix do deps.get, ecto.create, ecto.migrate, phx.server
  tests:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: test
    env_file:
      - .env
    volumes:
      - .:/app
